### ISSUE TITLE
Embed Permutation Methods into GeneratorInstance

### ISSUE THREAD

**Issue by powerswing** [ztsv-av/general_model#10]
Embed permutation methods into **GeneratorInstance** as passed arguments using (_\*\*args_)

Logically, this must work as follows:
- user passes as many permutation methods into **GeneratorInstance** as they want using (_\*\*args_)
- each permutation is read from (_\*\*args_) and applied onto **xBatch** in sequence before return

*Maybe a list of permutations as argument works better, not sure... Think it over yourself*

**Comment by ztsv-av** [comment]
Done. It works, tested it myself in a test file. The neat thing is, it applies permutation on each single image randomly, whereas in birdclef2021 we applied permutation randomly on a whole batch (now it is 'for i in batchX:  if random < ...').
