### ISSUE TITLE
Optimize Object Detection Code

### ISSUE THREAD

**Issue by powerswing** [ztsv-av/general_model#17]
do the following with `objectDetection.py`:

- [x] transfer variables into `globalVariables.py`
- [x] delete rudimentary comments
- [x] delete unnecessary import
- [x] delete unnecessary variables
- [x] transfer model (like architecture and train) functions into separate class in `magic.py`
- [x] transfer helper functions (like box visualization) into `helpers.py`
- [x] transfer data preprocessing functions from `helpers.py` to `dataPreprocessing.py`
- [x] think about better architecture for `globalVariables.py`?

corrections:
 - [x] implement dataset creation functions in classification and detection training (using tensorflow)
 - [x] magic.py - change class to training function

**if you have questions on what to do with other stuff - ask here in comments**

**Comment by powerswing** [comment]
NICE WORK NIGGA

**Comment by ztsv-av** [comment]
done. closing issue
