### ISSUE TITLE
Code Image Permutations

### ISSUE THREAD

**Issue by powerswing** [ztsv-av/general_model#7]
Code the following image permutations

- [ ] rotation **rotateImage.py(...)**
- [ ] blur (simple, box and Gaussian types) **blurImage.py(...)**. Types to be passed as argument **type**
- [ ] one more image permutation technique (look on Kaggle)

*remember that permutations must be randomized on each function call*

**Comment by ztsv-av** [comment]
implemented 12 or something permutations
