### ISSUE TITLE
__getitem__() Method of GeneratorInstance() in generatorInstance.py Returns Arrays of Zeros for yBatch

### ISSUE THREAD

**Issue by powerswing** [ztsv-av/general_model#8]
The prelast line in **\_\_getitem\_\_()** method defines *yBatch* as an array of zeros, i.e.

`yBatch = np.zeros((xBatch.shape[0], self.numClasses))`

This variable should map onto dictionary *LABEL_TO_INTEGER* in **globalVariables.py**

**Comment by ztsv-av** [comment]
yBatch's shape should be ('num_of_files_in_a_batch', 'num_of_classes'), so that for each value (file) in xBatch (its shape is 'num_of_files_in_a_batch') we have a label. The line we have in our code is correct and we shouldn't map it onto dictionary LABEL_TO_INTEGER (LABEL_TO_INTEGER is just a dictionary of length NUM_CLASSES).

**Comment by ztsv-av** [comment]
'num_of_files_in_a_batch' is usually just a batch_size, but sometimes it is less that that value which is why we use 'xBatch.shape[0]'

**Comment by ztsv-av** [comment]
Reopened this issue for you to check.

**Comment by powerswing** [comment]
By mapping onto dictionary I meant zeros become ones, otherwise you have for each observation

`xBatch[i] -> yBatch[i] <=> xBatch[i] -> [0,0,0,0,...]`

where in reality it should be

`xBatch[i] -> yBatch[i] (mapped onto dict) <=> xBatch[i] -> [0,1,0,0,...]`

If we apply multilabelling (like we did when we combined multiple birds into one), then **GeneratorInstance** must return all zeros (which it is now), and those zeros must be mapped onto dictionary in the permutation method itself.

**Comment by ztsv-av** [comment]
fixed. For now, model solves multiclass problem, perhaps we can add another parameter (as bool or string like 'multiclass', 'multilabel') to change the way yBatch is created.
